== `go mod` not well supported in CI

Ideally, as described in https://medium.com/rungo/anatomy-of-modules-in-go-c8274d215c16[https://medium.com/rungo/anatomy-of-modules-in-go-c8274d215c16],
`go mod` is the best way to build and packaging.

However, within You company, there may be NO WAY to open access to all external repos, so `go mod download` will not work.

The workaround is using vendor mechanism, i.e., put the dependency packages to `vendor` folder. sigh!

So in local, you can use `go mod`, but just make sure you copy all dependencis to `vendor` before you check in to git.

== Put project under `~/go/src` ($GOPATH)

This is for locating the package. If your package is `httpgo`, and your project folder `httpgo`, then if your project
path is `$GOPATH/httpgo`, then to refer to the package, you need `httpgo/httpgo`.

----
httpgo
├── cmd
│   └── main.go
└── httpgo
    ├── server.go
    ├── server_test.go
    └── util.go
----

== Files for docker hub

The following files are used to build container, and run the test:

----
Dockerfile              (1)
docker-compose.test.yml (2)
run_docker_tests.sh     (3)
----

(1) docker build file
(2) define the service to run the container
(3) test `httpgo` endpoints within the container

== TODO

Using https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/mocking[mocking] to increase the code coverage:

* Add `type Logger interface` for logging and mock
* Factor out the logic for handling response to a function, so that we can test it

== Reference

* https://godoc.org/-/about[Add package to GoDoc]
* https://blog.golang.org/godoc-documenting-go-code[Godoc: documenting Go code]
* https://medium.com/@elliotchance/godoc-tips-tricks-cda6571549b[godoc: Tips & Tricks]
* https://github.com/yangwenmai/how-to-add-badge-in-github-readme[Adding badge for Travis-CI & GoReportCard & Coveralls]
* https://shields.io/category/issue-tracking[The shields.io for tracking]
* https://gist.github.com/lukas-h/2a5d00690736b4c3a7ba[Markdown License badges]
* https://docs.codecov.io/docs/team-bot[Install Codecov's GiHub App]
* https://codecov.io/gh/p4ali/httpgo[codecov.io for github]
* https://coveralls.io/github/p4ali/httpgo?branch=master[Coverall for github]
* https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository[Licensing a repository]
* https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/mocking[Learn go with tests - including Mocking]
* https://github.com/golang/mock[gomock]
* https://blog.cleancoder.com/uncle-bob/2014/05/10/WhenToMock.html[When to Mock by Robert C. Martin]
